import { computeTraderRead } from './trader-read.js';

function fmtFunding(v) {
  if (v == null || v === '' || v === '—') return '—';
  const n = Number(String(v).replace(/[%,+$]/g, ''));
  if (Number.isNaN(n)) return String(v);
  const pct = Math.abs(n) <= 1 ? n * 100 : n;
  return `${pct >= 0 ? '+' : ''}${pct.toFixed(4)}%`;
}

/** Builds the full plain-text report (same structure as Copy Report in the UI). */
export function formatReportText(reportData) {
  const report = reportData?.report || reportData;
  if (!report) return 'CMC AGENT HUB - Market Report\n(No data)';

  const s = report.snapshot || {};
  const a = report.anchors || {};
  const t = report.technicals || {};
  const l = report.leverage || {};
  const tr = report.traderRead || {};
  const signals = computeTraderRead(tr);

  const ts = report.generatedAt
    ? new Date(report.generatedAt).toLocaleString('fr-FR')
    : new Date().toLocaleString('fr-FR');

  const technicalsLine = `RSI(14): ${t.rsi14 || '—'} · MACD: ${t.macdHist || '—'} · Pivot: ${t.pivot || '—'}`;
  const btcDepthLine = `RSI ${tr.btcRsi ?? '—'} · SMA200 ${tr.btcMa200 ?? '—'} · S ${tr.btcSupport ?? '—'} / R ${tr.btcResistance ?? '—'}`;
  const leverageLine = `OI ${l.openInterest || '—'} (${l.oiChange24h || '—'}) · Funding ${fmtFunding(l.funding)}`;
  const liquidationsLine = `BTC 24h: ${l.liq24h || '—'}`;
  const holdersLine = `LT ${tr.btcLtHolderPct ?? '—'}% · Whales ${tr.btcWhaleConcentration ?? '—'}% · ${tr.btcHolderTrend || '—'}`;
  const institutionalLine = `BTC ETF AUM: ${l.etfBtc || 'n/a'}`;

  const narrativeLines = (report.narratives || []).map((n, i) => {
    const rank = n.rank ?? i + 1;
    return `#${rank} ${n.name} - ${n.mcap} - 24h ${n.change24h}`;
  });

  const newsLines = (report.btcNews || []).map((n) => `• ${n.title}${n.url ? ` (${n.url})` : ''}`);

  const lines = [
    'CMC AGENT HUB - Market Report',
    ts,
    '',
    `MARKET CAP: ${s.marketCap || '—'}`,
    `FEAR & GREED: ${s.fearGreed ?? '—'} (${s.fearLabel || '—'})`,
    `BTC DOMINANCE: ${s.btcDom || '—'}`,
    `BTC PRICE: $${a.btc?.price || '—'}`,
    `ETH PRICE: $${a.eth?.price || '—'}`,
    '',
    `TECHNICALS: ${technicalsLine}`,
    `BTC DEPTH: ${btcDepthLine}`,
    `LEVERAGE: ${leverageLine}`,
    `LIQUIDATIONS: ${liquidationsLine}`,
    `HOLDERS: ${holdersLine}`,
    `INSTITUTIONAL: ${institutionalLine}`,
    '',
    `BIAS: ${signals.bias}`,
    `SENTIMENT: ${signals.sentiment}`,
    `LEVERAGE SIGNAL: ${signals.leverage}`,
    `WHALE: ${signals.whale}`,
    `SETUP: ${signals.setup}`,
    '',
    'TRENDING NARRATIVES:',
    ...(narrativeLines.length ? narrativeLines : ['—']),
    '',
    'BTC NEWS:',
    ...(newsLines.length ? newsLines : ['—']),
    '',
    'Generated by CMC Agent Hub - market-report Skill + crypto-research Skill',
    '#CMCAgentHub @coinmarketcap',
  ];

  return lines.join('\n');
}